### ISSUE TITLE
Mysql "The user credentials were incorrect." user error 

### ISSUE THREAD

**Issue by KotypeyPyEdition** [deissh/osu-lazer#27]
**Describe the bug**
I provide valid password but server says error `'$1' in 'where clause'`

**Screenshots**
https://i.imgur.com/W7KRmXY.png

**Desktop (please complete the following information):**
 - OS: Ubuntu(Kubuntu) 
 - Version 18.04.4

**Comment by deissh** [comment]
API server support only PostgresSQL.
